exports.getGuildEmojis = require( "./getGuildEmojis" )
exports.decancerName = require( "./decancerName" )
exports.deleteLine = require( "./deleteLine" )
exports.makeEmoji = require( "./makeEmoji" )
exports.getGuilds = require( "./getGuilds" )
exports.request = require( "./request" )